### ISSUE TITLE
testdouble-chai

### ISSUE THREAD

**Issue by jasonkarns** [BaseCase/trying_out_test_double#1]
One of your 'eh', notes was wishing that your test would finish with an assertion instead of a testdouble `verify` (if I understood that correctly). And you mentioned that you typically use chai for the assertions.

There is a sugar library, [sinon-chai](https://github.com/domenic/sinon-chai), that adds methods to chai's Assertion object that mirror sinon double verifications.

instead of using sinon's verifications:

``` js
sinon.assertCalledWith(mySpy, "foo");
```

you can use an assertion on the double itself:

``` js
expect(mySpy).to.have.been.calledWith("foo");
```

Perhaps someone should create testdouble-chai that adds similar assertion methods to chai that invoke testdouble's verifications under the covers. *wink wink*

**Comment by BaseCase** [comment]
Hey good idea! :)

**Comment by BaseCase** [comment]
https://github.com/BaseCase/testdouble-chai

**Comment by searls** [comment]
Hey @BaseCase would you mind making this?

**Comment by BaseCase** [comment]
@searls Not at all! I put this on my Big List o' Projects a few weeks back and then got bogged down in other stuff, but I'm about to finish my current thing so I'll bump it back up :)

**Comment by BaseCase** [comment]
Oh heyyyy took me several weeks longer to get to this than I planned on, but I finally got to it! https://github.com/BaseCase/testdouble-chai is a thing now; just gotta do a little housekeeping in there to make it publicly consumable, but it should be ready to use within a couple of hours :)

**Comment by searls** [comment]
Great!
